### ISSUE TITLE
macOS and DEBUG

### ISSUE THREAD

**Issue by JanX2** [debevv/nanoMODBUS#21]
I’ve been working on getting nanoMODBUS to work on macOS and it seems to be working fine. I used the Linux files as a template. 

There is still one annoyance that’s in the way. And more testing. 

nanoMODBUS defines the DEBUG() macro while Apple platforms define this as a flag for debug builds (#if DEBUG…). Any chance this could be renamed to NDEBUG or something similar?

**Comment by debevv** [comment]
Fixed in 920d25858db0f3c117967a981dfd5f860055ef7f

**Comment by debevv** [comment]
@JanX2 thank you
