### ISSUE TITLE
Using NMBS_SERVER_DISABLED

### ISSUE THREAD

**Issue by rik702** [debevv/nanoMODBUS#23]
I’ve written a Modbus RTU client in MacOS that works well.  As a Modbus newbie I started experimenting with the compiler flags and found if I set NMBS_SERVER_DISABLED, this stopped nmbs_read_holding_registers being available.  That confused me as I thought that would be a client function?

**Comment by debevv** [comment]
Yup, I noticed this too just yesterday, it doesn't make much sense. I'm going to fix this asap

**Comment by rik702** [comment]
Great, thanks
