### ISSUE TITLE
return type for nmbs_create

### ISSUE THREAD

**Issue by rlstrand** [debevv/nanoMODBUS#27]
nmbs_create is declared:

int nmbs_create(nmbs_t* nmbs, const nmbs_platform_conf* platform_conf) 

All the return values are of nmbs_error enum type.  Should most likely be:

nmbs_error nmbs_create(nmbs_t* nmbs, const nmbs_platform_conf* platform_conf)

**Comment by debevv** [comment]
44f319173566f01e56355c0031a75f6609b95b57
