### ISSUE TITLE
Doubts regarding the TCP connection in library

### ISSUE THREAD

**Issue by urrudelu30** [debevv/nanoMODBUS#49]
Hi, I am trying to find a Modbus IP library to fork it in my project SMT32. I also see that this project could work in client/server side and with RTU/IP mode, so I think it could be a good match. For me understanding, I could see that there is needed a **my_connect_tcp**, this function may be implemented by myself, is it correct?, maybe I can use LWIP stack or did you implemented it in your code?. Please help me to understand your library.

// Set up the TCP connection
    void* conn = my_connect_tcp(argv[1], argv[2]);
    if (!conn) {
        fprintf(stderr, "Error connecting to server\n");
        return 1;
    }

    // my_transport_read() and my_transport_write() are implemented by the user 
    nmbs_platform_conf platform_conf;
    platform_conf.transport = NMBS_TRANSPORT_TCP;
    platform_conf.read = my_transport_read;
    platform_conf.write = my_transport_write;
    platform_conf.arg = conn;    // Passing our TCP connection handle to the read/write functions

    // Create the modbus client
    nmbs_t nmbs;
    nmbs_error err = nmbs_client_create(&nmbs, &platform_conf);
    if (err != NMBS_ERROR_NONE) {
        fprintf(stderr, "Error creating modbus client\n");
        return 1;
    }

Thak you so much.

Looking formward to your response,

Regards,
Aitor

**Comment by debevv** [comment]
Closing this, if you have more questions feel free to reopen the issue
