### ISSUE TITLE
Configuration define error

### ISSUE THREAD

**Issue by awe-obdo** [debevv/nanoMODBUS#52]
v1.17.1

Hi,
There is an error on a configuration define in the *handle_req_fc* function, line 1763.
Currently:
```
#ifndef NMBS_SERVER_WRITE_MULTIPLE_COILS_DISABLED
```
Should be:
```
#ifndef NMBS_SERVER_READ_COILS_DISABLED
```

Regards,
Alain.

**Comment by debevv** [comment]
Fixedin f0a4374ac5fe58a5e3583bccb352be140fc36b73, thank you
