### ISSUE TITLE
Recover from link drop

### ISSUE THREAD

**Issue by mikestrauser** [debevv/nanoMODBUS#56]
Hello,

We have successfully merged nanoMODBUS into our STM32F4 project (using FreeRTOS and lwIP).  However, sometime when the link drops momentarily nanoMODBUS does not recover.  I have code that checks the PHY to see if the link is active, if not, it sets the netif down then the link and when it goes back active it sets them back up.  Is there something that should be done when this happens to restore nanoMODBUS operation?

Mike.

**Comment by debevv** [comment]
Hi, can you check the read/write platform functions are still called, or if the code is stuck inside of one of them?  
Alternately, try to setup again nanomodbus. Like, after the connection is reestablished make a new instance and redo the setup (addresses, callbacks, etc.)  
In general, there shouldn't be any internal state preventing the library from working. At worst, you could get an error and then the next operation should go on successfully.
