### ISSUE TITLE
Modbus TCP client over Wifi for Raspberry Pi Pico W (RP2040)

### ISSUE THREAD

**Issue by francdoc** [debevv/nanoMODBUS#57]
## Scope

The aim of this project is to implement the missing functionality needed to interact with a [Modbus TCP Linux server](https://github.com/debevv/nanoMODBUS/blob/master/examples/linux/server-tcp.c) using a Modbus TCP client via Wifi on the Raspberry Pi [Pico W](https://www.raspberrypi.com/products/raspberry-pi-pico/)'s on board CYW43439 wifi/bluetooth chip. 

The way this is to be done is by implementing (as explained in the README.md of the original repository) a port of **read_fd_pico**, **write_fd_pico** and **connect_tcp** for this specific microcontroller. 

## Background

The development target is the RP2040 microcontroller using the C programming language that comes in the Pico W board package.

The work done so far in this [branch](https://github.com/francdoc/nanoMODBUS/tree/rp2040-tcp-client/examples/pico) has been achieved by implementing some lwIP functions using **pico-examples** as reference: [lwIP WIFI source exaples](https://github.com/raspberrypi/pico-examples/tree/master/pico_w/wifi/tcp_client). 

Any help for getting a successful connection would be greatly appreciated.

**Comment by debevv** [comment]
Since you are on linux a good start would be checking out the linux code in the examples folder. Is there something in particular you'd like to know?

**Comment by francdoc** [comment]
Hi @debevv, thank you for your answer. Yes, I checked them and I'm in the process of making a port of this [file](https://github.com/debevv/nanoMODBUS/blob/master/examples/linux/client-tcp.c) and this [file](https://github.com/debevv/nanoMODBUS/blob/master/examples/linux/platform.h) for rp2040. I was wondering if you could help me.

I explained in detail above the situation. The idea is to have a linux server running this [program ](https://github.com/debevv/nanoMODBUS/blob/master/examples/linux/server-tcp.c)and to have the rp2040 writing modbus tcp registers as a client so the server can read them.

I would appreciate any help you can give me making this port, I started the work [here](https://github.com/francdoc/nanoMODBUS/tree/rp2040-tcp-client/examples/pico/app).

**Comment by francdoc** [comment]
Hi, I've just pushed a [Modbus RTU port](https://github.com/francdoc/nanoMODBUS/blob/rp2040-rtu-client/examples/pico/app/rtu-client.c) for the RP2040 (Pico). Check it out if you are interested.

**Comment by debevv** [comment]
Merged in 7e4ef3e97e39664759e14bf993ff60d51dc8d850. Thank you

**Comment by francdoc** [comment]
Great, thank you
