### ISSUE TITLE
cppcheck-reported issue

### ISSUE THREAD

**Issue by escherstair** [debevv/nanoMODBUS#76]
I used [cppcheck](https://cppcheck.sourceforge.io/) to perform a static analysis of the source code and I see this issue:

- identicalConditionAfterEarlyExit - CWE: 398

at line 1453
https://github.com/debevv/nanoMODBUS/blob/cfc1dd00c8648ebffc2b1160c66af803e98f82d8/nanomodbus.c#L1453-L1454

This is because if `request_size > 251` the fuction has already returned here
https://github.com/debevv/nanoMODBUS/blob/cfc1dd00c8648ebffc2b1160c66af803e98f82d8/nanomodbus.c#L1432-L1434

and so it's not necessary checking again `request_size` range.

**Comment by debevv** [comment]
Fixed in 9b93660e81ad30144e3c02246863e3a42ceb3610. Thank you
